import 'package:coursewave/model/course.dart';

var EducationCourses = [
  // Your existing courses go here
  Course(
    courseName: 'Data Science Fundamentals',
    instructor: 'Prof. Jane Doe',
    duration: '12 weeks',
    startDate: '2024-07-01',
    endDate: '2024-09-23',
    fee: 800,
    numSessions: 24,
    level: 'Intermediate',
    description:
        'Learn the fundamental concepts of data science, including data analysis, visualization, and machine learning using R.',
    platform: 'Online',
    lesson1Name: 'Introduction to Data Science',
    lesson1Introduction: 'Overview of data science applications.',
    lesson2Name: 'Data Analysis with R',
    lesson2Introduction: 'Perform data analysis with R.',
    lesson3Name: 'Data Visualization Techniques',
    lesson3Introduction: 'Techniques for effective data visualization.',
    image: 'assets/images/course/b.png',
    theory: '60 H',
    practical: '60 H',
    timeRequired: '10 hours per week',
  ),
  Course(
    courseName: 'Digital Marketing Mastery',
    instructor: 'Mr. Alex Johnson',
    duration: '18 H',
    startDate: '2024-05-20',
    endDate: '2024-07-14',
    fee: 600,
    numSessions: 16,
    level: 'Advanced',
    description:
        'Master the skills needed for digital marketing, including SEO, social media marketing, and content strategy.',
    platform: 'Online',
    lesson1Name: 'Introduction to SEO',
    lesson1Introduction: 'Basics of search engine optimization.',
    lesson2Name: 'Social Media Marketing Strategies',
    lesson2Introduction: 'Effective strategies for social media.',
    lesson3Name: 'Content Creation Techniques',
    lesson3Introduction: 'Techniques for compelling content creation.',
    image: 'assets/images/course/a.png',
    theory: '10 H',
    practical: '8 H',
    timeRequired: '2 hours per session',
  ),
  Course(
    courseName: 'Web Development Bootcamp',
    instructor: 'Ms. Lily Taylor',
    duration: '15 H',
    startDate: '2024-04-15',
    endDate: '2024-05-31',
    fee: 450,
    numSessions: 12,
    level: 'Beginner',
    description:
        'A comprehensive introduction to web development, covering HTML, CSS, JavaScript, and responsive design.',
    platform: 'Online',
    lesson1Name: 'HTML Basics',
    lesson1Introduction: 'Fundamentals of HTML structure.',
    lesson2Name: 'CSS Styling',
    lesson2Introduction: 'Style web pages using CSS.',
    lesson3Name: 'JavaScript Interactivity',
    lesson3Introduction: 'Add interactivity with JavaScript.',
    image: 'assets/images/course/c.png',
    theory: '8 H',
    practical: '7 H',
    timeRequired: '1.5 hours per session',
  ),
  Course(
    courseName: 'Machine Learning Essentials',
    instructor: 'Dr. Emily White',
    duration: '10 weeks',
    startDate: '2024-03-01',
    endDate: '2024-04-11',
    fee: 700,
    numSessions: 20,
    level: 'Intermediate',
    description:
        'An introduction to machine learning algorithms and their applications in real-world scenarios.',
    platform: 'Online',
    lesson1Name: 'Introduction to Machine Learning',
    lesson1Introduction: 'Understand machine learning importance.',
    lesson2Name: 'Supervised Learning',
    lesson2Introduction: 'Learn about supervised learning methods.',
    lesson3Name: 'Unsupervised Learning',
    lesson3Introduction: 'Explore unsupervised learning techniques.',
    image: 'assets/images/course/d.png',
    theory: '48 H',
    practical: '32 H',
    timeRequired: '8 hours per week',
  ),
  Course(
    courseName: 'Cybersecurity Fundamentals',
    instructor: 'Mr. Frank Green',
    duration: '8 weeks',
    startDate: '2024-02-15',
    endDate: '2024-04-11',
    fee: 650,
    numSessions: 16,
    level: 'Advanced',
    description:
        'Gain a solid understanding of cybersecurity principles and best practices to protect systems and networks.',
    platform: 'Online',
    lesson1Name: 'Understanding Cybersecurity',
    lesson1Introduction: 'Basics of cybersecurity importance.',
    lesson2Name: 'Network Security',
    lesson2Introduction: 'Network security measures and protocols.',
    lesson3Name: 'Threats and Vulnerabilities',
    lesson3Introduction: 'Identify common threats and vulnerabilities.',
    image: 'assets/images/course/e.png',
    theory: '30 H',
    practical: '18 H',
    timeRequired: '6 hours per week',
  ),
];
